from tkinter import*

root=Tk()
root.geometry('900x633')
root.title('\'LoVeLink\'')
Label(root,text='REGISTER NEW MEMBER',font='comicsansms 15 bold',fg='red',padx=10,pady=10).grid(row=0,column=3)
#create  labels'

fname=Label(root,text='First name :')
lname=Label(root,text='Last name :')
Label(root,text='Gender').grid(row=3,column=0)
gender=Label(root,text='Female / Male :')
Label(root,text='Looking for').grid(row=5,column=0)
malefe=Label(root,text='Male / Female :')
birth=Label(root,text='Date of Birth').grid(row=7,column=0)
month=Label(root,text='Month :')
day=Label(root,text='Day :')
year=Label(root,text='Year :')
religion=Label(root,text='Religion :')
education=Label(root,text='Education :')
country=Label(root,text='Country :')
password=Label(root,text='Password :')
confirmpass=Label(root,text='Confirm Password :')
Label(root,text='SIGN UP WITH EMAIL',font='Helvetica 10 bold',fg='white',bg='red').grid(row=19,column=1)
Label(root,text='SIGN IN GOOGLE',font='Helvetica 10 bold',fg='grey',bg='white').grid(row=21,column=2)

#create entry fields
fname_entry=Entry(root)
lname_entry=Entry(root)
gender_entry=Entry(root)
malefe_entry=Entry(root)
month_entry=Entry(root)
day_entry=Entry(root)
year_entry=Entry(root)
religion_entry=Entry(root)
education_entry=Entry(root)
country_entry=Entry(root)
password_entry=Entry(root)
confirmpass_entry=Entry(root)

#create submit button
def submit():
    fname=fname_entry.get()
    lname=lname_entry.get()
    gender=gender_entry.get()
    malefe=malefe_entry.get()
    month=month_entry.get()
    day=day_entry.get()
    year=year_entry.get()
    religion=religion_entry.get()
    education=education_entry.get()
    country=country_entry.get()
    password=password_entry.get()
    confirmpass=confirmpass_entry.get()
    print('it works!')       

          
submit_button=Button(root,text='Submit',command=submit)          
#grid layout for label,entry fields and submit button
          
fname.grid(row=1,column=0)
fname_entry.grid(row=1,column=1)
lname.grid(row=2,column=0)
lname_entry.grid(row=2,column=1)
gender.grid(row=4,column=0)
gender_entry.grid(row=4,column=1)
malefe.grid(row=6,column=0)
malefe_entry.grid(row=6,column=1)
month.grid(row=8,column=0)
month_entry.grid(row=8,column=1)
day.grid(row=9,column=0)
day_entry.grid(row=9,column=1)
year.grid(row=10,column=0)
year_entry.grid(row=10,column=1)
religion.grid(row=11,column=0)
religion_entry.grid(row=11,column=1)
education.grid(row=12,column=0)
education_entry.grid(row=12,column=1)
country.grid(row=13,column=0)
country_entry.grid(row=13,column=1)
password.grid(row=14,column=0)
password_entry.grid(row=14,column=1)
confirmpass.grid(row=15,column=0)
confirmpass_entry.grid(row=15,column=1)
submit_button.grid(row=17,column=1)         
          

root.mainloop()
